node {
    def server = Artifactory.server('orange.australiaeast.cloudapp.azure.com')
    def rtGradle = Artifactory.newGradleBuild()
    def buildInfo = Artifactory.newBuildInfo()
    stage 'Build'
        git url: 'https://github.com/sammyboyzzz001/my-orange-jenkins.git'
        
    stage 'Artifactory configuration'
        // Tool name from Jenkins configuration > Global Tool Configuration > Gradle
        rtGradle.tool = 'my_gradle'
        // As per defined under my-orange-gsgradle/artifactory/build.gradle
        rtGradle.deployer repo:'gradle-gradle-dev-local',  server: server
        rtGradle.resolver repo:'gradle-gradle-dev', server: server

        stage('Config Build Info') {
            buildInfo.env.capture = true
            buildInfo.env.filter.addInclude("*")
        }

        stage('Extra gradle configurations') {
            rtGradle.usesPlugin = true // Artifactory plugin already defined in build script
        }
        stage('Exec Gradle') {
            rtGradle.run rootDir: "artifactory/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish', buildInfo: buildInfo
        }
        stage('Publish build info') {
            server.publishBuildInfo buildInfo
        }
}
